replicaCount: 1

image:
  repository: vinicpires/foobar-api
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  port: 443
  targetPort: 80

ingress:
  enabled: true
  host: foobar.localhost
  entryPoint: websecure

persistence:
  enabled: true
  accessModes: ["ReadWriteOnce"]
  size: 128Mi
  storageClassName: ""

tlsSecret:
  enabled: true
  name: ""
  crtKey: tls.crt
  keyKey: tls.key
  crtFile: ""
  keyFile: ""

# Caminho final no PVC onde o app espera encontrar os arquivos
certs:
  mountPath: /cert
  certFilename: cert.pem
  keyFilename: key.pem

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
