{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "foobar-api.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foobar-api.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint }}
  routes:
    - match: HostSNI(`{{ .Values.ingress.host }}`)
      services:
        - name: {{ include "foobar-api.fullname" . }}-service
          port: {{ .Values.service.port }}
  tls:
    passthrough: true
{{- end -}}
