{{- if .Values.tlsSecret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foobar-api.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "foobar-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.tlsSecret.crtKey }}: |-
{{ required "tlsSecret.crtFile is required (use --set-file tlsSecret.crtFile=...)" .Values.tlsSecret.crtFile | nindent 4 }}
  {{ .Values.tlsSecret.keyKey }}: |-
{{ required "tlsSecret.keyFile is required (use --set-file tlsSecret.keyFile=...)" .Values.tlsSecret.keyFile | nindent 4 }}
{{- end -}}
